name: Cucumber Appium CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests and generate Extent Reports
        run: mvn verify # Update this with your specific Maven command to run tests and generate reports

      - name: Upload Extent Reports to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: extent-reports
          path: test-output/SparkReport/*.html # Ensure this path matches where your Extent Reports are saved

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-output/SparkReport # Ensure this path matches where your Extent Reports are saved
          publish_branch: gh-pages # The branch the action should deploy to
          keep_files: false # Set to true if you want to keep existing files in the branch
